# core/instance_specs.py
# AWS EC2 instance type specifications lookup
# Source: AWS official pricing (ap-south-1 on-demand Linux)
# Add new instance types here as needed

INSTANCE_SPECS = {
    "t2.micro":    {"vcpu": 1,  "ram_gb": 1,    
                    "network": "Low",          
                    "on_demand_hourly": 0.0116},
    "t2.small":    {"vcpu": 1,  "ram_gb": 2,    
                    "network": "Low to Moderate", 
                    "on_demand_hourly": 0.0230},
    "t2.medium":   {"vcpu": 2,  "ram_gb": 4,    
                    "network": "Low to Moderate", 
                    "on_demand_hourly": 0.0464},
    "t2.large":    {"vcpu": 2,  "ram_gb": 8,    
                    "network": "Low to Moderate", 
                    "on_demand_hourly": 0.0928},
    "t2.xlarge":   {"vcpu": 4,  "ram_gb": 16,   
                    "network": "Moderate",     
                    "on_demand_hourly": 0.1856},
    "t3.micro":    {"vcpu": 2,  "ram_gb": 1,    
                    "network": "Up to 5 Gbps", 
                    "on_demand_hourly": 0.0104},
    "t3.small":    {"vcpu": 2,  "ram_gb": 2,    
                    "network": "Up to 5 Gbps", 
                    "on_demand_hourly": 0.0208},
    "t3.medium":   {"vcpu": 2,  "ram_gb": 4,    
                    "network": "Up to 5 Gbps", 
                    "on_demand_hourly": 0.0416},
    "t3.large":    {"vcpu": 2,  "ram_gb": 8,    
                    "network": "Up to 5 Gbps", 
                    "on_demand_hourly": 0.0832},
    "t3.xlarge":   {"vcpu": 4,  "ram_gb": 16,   
                    "network": "Up to 5 Gbps", 
                    "on_demand_hourly": 0.1664},
    "t3.2xlarge":  {"vcpu": 8,  "ram_gb": 32,   
                    "network": "Up to 5 Gbps", 
                    "on_demand_hourly": 0.3328},
    "t3a.micro":   {"vcpu": 2,  "ram_gb": 1,    
                    "network": "Up to 5 Gbps", 
                    "on_demand_hourly": 0.0094},
    "t3a.small":   {"vcpu": 2,  "ram_gb": 2,    
                    "network": "Up to 5 Gbps", 
                    "on_demand_hourly": 0.0188},
    "t3a.medium":  {"vcpu": 2,  "ram_gb": 4,    
                    "network": "Up to 5 Gbps", 
                    "on_demand_hourly": 0.0376},
    "t3a.large":   {"vcpu": 2,  "ram_gb": 8,    
                    "network": "Up to 5 Gbps", 
                    "on_demand_hourly": 0.0752},
    "m5.large":    {"vcpu": 2,  "ram_gb": 8,    
                    "network": "Up to 10 Gbps",
                    "on_demand_hourly": 0.096},
    "m5.xlarge":   {"vcpu": 4,  "ram_gb": 16,   
                    "network": "Up to 10 Gbps",
                    "on_demand_hourly": 0.192},
    "m5.2xlarge":  {"vcpu": 8,  "ram_gb": 32,   
                    "network": "Up to 10 Gbps",
                    "on_demand_hourly": 0.384},
    "m5.4xlarge":  {"vcpu": 16, "ram_gb": 64,   
                    "network": "Up to 10 Gbps",
                    "on_demand_hourly": 0.768},
    "m5a.large":   {"vcpu": 2,  "ram_gb": 8,    
                    "network": "Up to 10 Gbps",
                    "on_demand_hourly": 0.086},
    "m5a.xlarge":  {"vcpu": 4,  "ram_gb": 16,   
                    "network": "Up to 10 Gbps",
                    "on_demand_hourly": 0.172},
    "m5a.2xlarge": {"vcpu": 8,  "ram_gb": 32,   
                    "network": "Up to 10 Gbps",
                    "on_demand_hourly": 0.344},
    "m4.large":    {"vcpu": 2,  "ram_gb": 8,    
                    "network": "Moderate",     
                    "on_demand_hourly": 0.100},
    "m4.xlarge":   {"vcpu": 4,  "ram_gb": 16,   
                    "network": "High",         
                    "on_demand_hourly": 0.200},
    "m4.2xlarge":  {"vcpu": 8,  "ram_gb": 32,   
                    "network": "High",         
                    "on_demand_hourly": 0.400},
    "c5.large":    {"vcpu": 2,  "ram_gb": 4,    
                    "network": "Up to 10 Gbps",
                    "on_demand_hourly": 0.085},
    "c5.xlarge":   {"vcpu": 4,  "ram_gb": 8,    
                    "network": "Up to 10 Gbps",
                    "on_demand_hourly": 0.170},
    "c5.2xlarge":  {"vcpu": 8,  "ram_gb": 16,   
                    "network": "Up to 10 Gbps",
                    "on_demand_hourly": 0.340},
    "c5.4xlarge":  {"vcpu": 16, "ram_gb": 32,   
                    "network": "Up to 10 Gbps",
                    "on_demand_hourly": 0.680},
    "c5a.large":   {"vcpu": 2,  "ram_gb": 4,    
                    "network": "Up to 10 Gbps",
                    "on_demand_hourly": 0.077},
    "c5a.xlarge":  {"vcpu": 4,  "ram_gb": 8,    
                    "network": "Up to 10 Gbps",
                    "on_demand_hourly": 0.154},
    "r5.large":    {"vcpu": 2,  "ram_gb": 16,   
                    "network": "Up to 10 Gbps",
                    "on_demand_hourly": 0.126},
    "r5.xlarge":   {"vcpu": 4,  "ram_gb": 32,   
                    "network": "Up to 10 Gbps",
                    "on_demand_hourly": 0.252},
    "r5.2xlarge":  {"vcpu": 8,  "ram_gb": 64,   
                    "network": "Up to 10 Gbps",
                    "on_demand_hourly": 0.504},
    "r4.large":    {"vcpu": 2,  "ram_gb": 15.25,
                    "network": "Up to 10 Gbps",
                    "on_demand_hourly": 0.133},
    "r4.xlarge":   {"vcpu": 4,  "ram_gb": 30.5, 
                    "network": "Up to 10 Gbps",
                    "on_demand_hourly": 0.266},
}


def get_instance_specs(instance_type: str) -> dict:
    """
    Returns spec dict for a given instance type.
    Returns empty dict if instance type not found — never raises.
    Frontend handles missing specs gracefully.
    """
    return INSTANCE_SPECS.get(instance_type, {})
